CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "public"."people_v6" (
  "name" TEXT,
  "surname" TEXT,
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "uuid_v1" UUID DEFAULT uuid_generate_v1() UNIQUE,
  "uuid_v4" UUID DEFAULT uuid_generate_v4() UNIQUE
);